# port
server:
  port: 8088

spring:
  jpa:
    database: mysql   # 추가 해준 부분
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  config:
    import: application-local.yml # DB, Kakao
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix=: .jsp
    hiddenmethod:
      filter:
        enabled: true # put, delete 메소드 사용하기 위함
kakao:
  redirectUrl: http://localhost:8088/oauth/token

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace


#  jpa:   #oracle
#    database: oracle
#    database-platform: org.hibernate.dialect.Oracle12cDialect
#  tomcat:
#    additional-tld-skip-patterns:
#      - oraclepki.jar
#      - osdt_core.jar
#      - osdt_cert.jar