# port
server:
  port: 8088
  tomcat:
    additional-tld-skip-patterns:
      - oraclepki.jar
      - osdt_core.jar
      - osdt_cert.jar
spring:
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  config:
    import: application-local.yml # DB, Kakao
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix=: .jsp
kakao:
  redirectUrl: http://localhost:8088/oauth/token

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace